# Generated by Django 3.2.5 on 2022-04-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='username',
        ),
    ]
