# Generated by Django 3.2.5 on 2022-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_ticket_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Done'), (2, 'Not done'), (3, 'Frozen')], default='2'),
            preserve_default=False,
        ),
    ]
