# Generated by Django 3.2.5 on 2022-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Done'), (2, 'Not done'), (3, 'Frozen')]),
        ),
    ]
